### PR TITLE
Give feedback to unhelpful posts

### PR DESCRIPTION
**Pull request by braxtonhall**
does what it says on the tin

### CODE REVIEW

**Comment by markusdemedeiros** [comment]
I review this to be ✅

**Review by markusdemedeiros — APPROVED** [review]
looks good to me

**Review by nritschel — DISMISSED** [review]
Beautiful. A true work of art.

**Review by nritschel — APPROVED** [review]
Still beautiful. An even truer work of art.

**Comment by rtholmes** [comment]
I do appreciate the effort put into unit testing this, although I can't imagine this actually being triggered in practice.

**Pull request merged**
